# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Q5_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
import matplotlib.image as img
import os
import tkinter
from tkinter import filedialog


class Ui_Q5_Window(object):
    def setupUi(self, Q5_Window):
        Q5_Window.setObjectName("Q5_Window")
        Q5_Window.resize(197, 315)
        self.centralwidget = QtWidgets.QWidget(Q5_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.Q5 = QtWidgets.QGroupBox(self.centralwidget)
        self.Q5.setGeometry(QtCore.QRect(10, 15, 180, 285))
        self.Q5.setObjectName("Q5")
        self.Button_5_1 = QtWidgets.QPushButton(self.Q5)
        self.Button_5_1.setGeometry(QtCore.QRect(10, 20, 160, 25))
        self.Button_5_1.setObjectName("Button_5_1")
        self.Button_5_1.clicked.connect(self.buttonclik_5_1)

        self.Button_5_3 = QtWidgets.QPushButton(self.Q5)
        self.Button_5_3.setGeometry(QtCore.QRect(10, 110, 160, 25))
        self.Button_5_3.setObjectName("Button_5_3")
        #self.Button_5_3.clicked.connect(self.buttonclik_5_3)

        self.Button_5_4 = QtWidgets.QPushButton(self.Q5)
        self.Button_5_4.setGeometry(QtCore.QRect(10, 155, 160, 25))
        self.Button_5_4.setObjectName("Button_5_4")
        #self.Button_5_4.clicked.connect(self.buttonclik_5_4)

        self.Button_5_2 = QtWidgets.QPushButton(self.Q5)
        self.Button_5_2.setGeometry(QtCore.QRect(10, 65, 160, 25))
        self.Button_5_2.setObjectName("Button_5_2")
        #self.Button_5_2.clicked.connect(self.buttonclik_5_2)

        self.Button_5_6 = QtWidgets.QPushButton(self.Q5)
        self.Button_5_6.setGeometry(QtCore.QRect(10, 245, 160, 25))
        self.Button_5_6.setObjectName("Button_5_6")
        #self.Button_5_6.clicked.connect(self.buttonclik_5_6)

        self.Button_5_5 = QtWidgets.QPushButton(self.Q5)
        self.Button_5_5.setGeometry(QtCore.QRect(10, 200, 160, 25))
        self.Button_5_5.setObjectName("Button_5_5")
        #self.Button_5_5.clicked.connect(self.buttonclik_5_5)

        Q5_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Q5_Window)
        QtCore.QMetaObject.connectSlotsByName(Q5_Window)

    def buttonclik_5_1(self):
        #貓
        plt.subplot(1,2,1)
        plt.title("cat")
        os.chdir('C:\Users\USER\Documents\python\.VScode\Hw2_F64101032_黃薇庭_V1\Dataset_OpenCvDl_Hw2_Q5\Dataset_OpenCvDl_Hw2_Q5\inference_dataset\Cat')
        img_cat=img.imread('8043.jpg')
        plt.imshow(img_cat)
        plt.axis('off')
        #狗
        plt.subplot(1,2,2)
        plt.title("dog")
        os.chdir('C:\Users\USER\Documents\python\.VScode\Hw2_F64101032_黃薇庭_V1\Dataset_OpenCvDl_Hw2_Q5\Dataset_OpenCvDl_Hw2_Q5\inference_dataset\Dog')
        img_dog=img.imread('12051.jpg')
        plt.imshow(img_dog)
        plt.axis('off')
        plt.show()
    
    #def buttonclik_5_2(self):
    
    #def buttonclik_5_3(self):
    
    #def buttonclik_5_4(self):
    
    #def buttonclik_5_5(self):

    def retranslateUi(self, Q5_Window):
        _translate = QtCore.QCoreApplication.translate
        Q5_Window.setWindowTitle(_translate("Q5_Window", "Q5"))
        self.Q5.setTitle(_translate("Q5_Window", "5.ResNet50"))
        self.Button_5_1.setText(_translate("Q5_Window", "Load Image "))
        self.Button_5_3.setText(_translate("Q5_Window", "2. Show Distribution"))
        self.Button_5_4.setText(_translate("Q5_Window", "3. Show Model Structure"))
        self.Button_5_2.setText(_translate("Q5_Window", "1. Show Image"))
        self.Button_5_6.setText(_translate("Q5_Window", "5. Inference"))
        self.Button_5_5.setText(_translate("Q5_Window", "4. Show Comparison"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Q5_Window = QtWidgets.QMainWindow()
    ui = Ui_Q5_Window()
    ui.setupUi(Q5_Window)
    Q5_Window.show()
    sys.exit(app.exec_())
